# Generated by Django 3.2.25 on 2024-10-03 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.CharField(default=events.models.generate_snowflake_id, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('ME', 'One-Off'), ('WE', 'One-on-One')], default='WE', max_length=2)),
                ('event_occurrence_type', models.CharField(choices=[('BD', 'Between 2 dates'), ('LD', 'List of Dates'), ('RE', 'Recurring')], default='BD', max_length=2)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(default=30)),
                ('event_dates', models.JSONField(blank=True, default=list, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
