# Generated by Django 5.1.1 on 2024-10-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_googlecredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredentials',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='token_uri',
        ),
    ]
