# Generated by Django 5.1.1 on 2024-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_googlecredentials_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='token_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='googlecredentials',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
