# Generated by Django 3.2.25 on 2024-10-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_googlecredentials_client_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
